CC=gcc

kilo: kilo.c
	$(CC) kilo.c -o kilo -Wall -Wextra -pedantic -std=c99

#CC=gcc adalah variable compiler, untuk kali ini saya menggunakan gcc yg all in one compiler.
#kilo adalah binary yang akan dibuat, sedang kilo.c adalah kode yang akan di proses. 
#$(CC) digunakan untuk menggunakan variable CC yg sebelumnya di set untuk menggunakan gcc.
#-Wall all-warning, digunakan untuk menjelaskan bahwa mungkin secara teknis kode nya berjalan namun terhitung buruk.
# -Wextra -pedantic memberikan peringatan ekstra.
#  -std=c99 menggunakan standard bahasa c99 yg dirilis 1999.
